version: '3'
services:

  # Base Images

  php56-fpm-stretch-base:
    build:
      context: ./
      dockerfile: base.Dockerfile
    image: my127/wordpress:5.6-fpm-stretch

  php70-fpm-stretch-base:
    build:
      context: ./
      dockerfile: base.Dockerfile
    image: my127/wordpress:7.0-fpm-stretch
  
  php71-fpm-stretch-base:
    build:
      context: ./
      dockerfile: base.Dockerfile
    image: my127/wordpress:7.1-fpm-stretch

  php72-fpm-stretch-base:
    build:
      context: ./
      dockerfile: base.Dockerfile
    image: my127/wordpress:7.2-fpm-stretch

  php73-fpm-stretch-base:
    build:
      context: ./
      dockerfile: base.Dockerfile
    image: my127/wordpress:7.3-fpm-stretch

  # Console Images

  php56-fpm-stretch-console:
    build:
      context: ./
      dockerfile: console.Dockerfile
    image: my127/wordpress:5.6-fpm-stretch-console
    depends_on:
      - php56-fpm-stretch-base

  php70-fpm-stretch-console:
    build:
      context: ./
      dockerfile: console.Dockerfile
    image: my127/wordpress:7.0-fpm-stretch-console
    depends_on:
      - php70-fpm-stretch-base

  php71-fpm-stretch-console:
    build:
      context: ./
      dockerfile: console.Dockerfile
    image: my127/wordpress:7.1-fpm-stretch-console
    depends_on:
      - php71-fpm-stretch-base

  php72-fpm-stretch-console:
    build:
      context: ./
      dockerfile: console.Dockerfile
    image: my127/wordpress:7.2-fpm-stretch-console
    depends_on:
      - php72-fpm-stretch-base

  php73-fpm-stretch-console:
    build:
      context: ./
      dockerfile: console.Dockerfile
    image: my127/wordpress:7.3-fpm-stretch-console
    depends_on:
      - php73-fpm-stretch-base
